PKG: a) Removed all transition packages, since none of the earlier packages were shipped. b) Cleaned up files in debian/*, mostly removing scikit-learn references.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,50 +1,61 @@
 #!/usr/bin/make -f
 # -*- mode: makefile; coding: utf-8 -*-
+# skimage package debian/rules files is largely based on debian/rules from scikit-learn
 
-PACKAGE_NAME = python-scikits.image
-PACKAGE_ROOT_DIR = $(CURDIR)/debian/${PACKAGE_NAME}
+PACKAGE_NAME = python-skimage 
+PACKAGE_ROOT_DIR = debian/${PACKAGE_NAME}
 
 PYVERS = $(shell pyversions -vs)
 PYVER = $(shell pyversions  -vd)
 
 # Mega rule
 %:
-	dh $@ --buildsystem python_distutils
+	: # Explicit build system to avoid use of all-in-1 Makefile
+	dh $@ --buildsystem=python_distutils
+
 
 override_dh_clean:
-ifeq (,$(filter noclean,$(DEB_BUILD_OPTIONS)))
-	rm -rf build doc/build doc/auto_examples *-stamp scikits.image.egg-info
 	dh_clean
-endif
 
-# Prune toplevel scikits/__init__.py to avoid conflicts across future
-# scikits- packages, and rely on dh_python to create such one if
-# necessary
 
-# Build docs during install
-override_dh_auto_install: ${PYVERS:%=python-install%}
-	find debian -wholename \*scikits/__init__.py -delete
-
+override_dh_auto_install: ${PYVERS:%=python-install%} ${PYVERS:%=python-test%}
 # Per Python version logic -- install, test, move .so into -lib
 python-install%:
-	python$* setup.py install --install-layout=deb --root=$(PACKAGE_ROOT_DIR)
+	python$* setup.py install --install-layout=deb --root=$(PACKAGE_ROOT_DIR)/
 
-	: # Build Documentation
-ifeq (,$(filter nodoc,$(DEB_BUILD_OPTIONS)))
-	export PYTHONPATH=$(PACKAGE_ROOT_DIR)/usr/lib/python$*/dist-packages MPLCONFIGDIR=$(CURDIR)/build HOME=$(CURDIR)/build; \
-	 cd doc; test -d build/html || $(MAKE) html
-	python$* setup.py install --install-layout=deb --root=$(PACKAGE_ROOT_DIR)
-endif
-
+python-test%: python-install%
 ifeq (,$(filter nocheck,$(DEB_BUILD_OPTIONS)))
-	: # Run unittests
-	export PYTHONPATH=$(PACKAGE_ROOT_DIR)/usr/lib/python$*/dist-packages; \
-	 python$* /usr/bin/nosetests -s \
-	  $(PACKAGE_ROOT_DIR)/usr/lib/python$*/*/scikits/image
+	: # Run unittests here against installed scikits.image
+	export PYTHONPATH=`/bin/ls -d $$PWD/$(PACKAGE_ROOT_DIR)/usr/lib/python$*/*/`; \
+	export MPLCONFIGDIR=$(CURDIR)/build HOME=$(CURDIR)/build; \
+	export JOBLIB_MULTIPROCESSING=0; \
+	cd build/; python$* /usr/bin/nosetests -s skimage && \
+			   { python$* /usr/bin/nosetests --with-doctest --doctest-extension=rst ../doc/ || : ; } # doctests are failing ATM
 else
 	: # Skip unittests due to nocheck
 endif
 
+
+override_dh_installdocs:
+	: # Build Documentation using installed scikits.image
+ifeq (,$(filter nodoc,$(DEB_BUILD_OPTIONS)))
+ifneq (,$(findstring -a,$(DH_INTERNAL_OPTIONS)))
+	: # not building documentation in -a
+else
+	export PYTHONPATH=`/bin/ls -d $$PWD/$(PACKAGE_ROOT_DIR)/usr/lib/python$(PYVER)/*`; \
+	export MPLCONFIGDIR=$(CURDIR)/build HOME=$(CURDIR)/build; \
+	 cd doc; $(MAKE) html
+endif
+endif
+	: # Use jquery from Debian package, so prune shipped one
+	-rm doc/_build/html/_static/jquery.js
+	dh_installdocs -A AUTHORS.rst README*.rst
+
+override_dh_installchangelogs:
+	dh_installchangelogs doc/whats_new.rst
+
+## move binary libraries into -lib
+override_dh_pysupport:
 	: # Move platform-specific libraries into -lib
 	for lib in $$(find $(PACKAGE_ROOT_DIR)/usr -name '*.so'); do \
 	   sdir=$$(dirname $$lib) ; \
@@ -53,26 +64,29 @@ endif
 	   echo "Moving '$$lib' into '$$tdir'." ; \
 	   mv $$lib $$tdir ; \
 	done
-
-	: # Use jquery and underscore from Debian package, so prune shipped one
-	-rm -f doc/build/html/_static/jquery.js
-	# Actually due to the problems with underscore pkg across releases just ship one for now
-	#-rm -f doc/build/html/_static/underscore.js
-	-rf -f doc/build/html/_sources
-	-rf -f doc/build/html/.buildinfo
-
-	: # Move documentation to -doc
-	sdir=$(CURDIR)/doc/build/html ; \
-	tdir=$(PACKAGE_ROOT_DIR)-doc/usr/share/doc/$(PACKAGE_NAME)-doc ; \
-	mkdir -p $$tdir ; \
-	echo "DOCS: Moving '$$sdir' into '$$tdir'." ; \
-	test -d $$tdir/html || mv $$sdir $$tdir
-
-	if [ -x /usr/bin/dh_numpy ]; then dh_numpy; fi
+	if [ -x /usr/bin/dh_numpy ]; then dh_numpy -ppython-skimage-lib; fi
+	: # Prune scikits/__init__.py to avoid conflicts
+	find debian -wholename \*scikits/__init__.py -delete
+	: # Move scikits. space into a compatibility package
+	find debian -wholename \*scikits -type d | while read skd; do \
+		skbd=$$(dirname $$skd); \
+		skbd_=$$(echo $$skbd | sed -e 's/skimage/scikits-image/g'); \
+		mkdir -p $$skbd_; \
+		mv $$skd $$skbd_; \
+	done
+	dh_pysupport
 
 ## immediately useable documentation and exemplar scripts/data
 override_dh_compress:
-	dh_compress -X.py -X.html -X.pdf -X.css -X.jpg -X.txt -X.js -X.json -X.rtc
+	dh_compress -X.py -X.html -X.pdf -X.css -X.jpg -X.txt -X.js -X.json -X.rtc -Xobjects.inv
 
-override_dh_installdocs:
-	dh_installdocs -A CONTRIBUTORS.txt README.txt DEVELOPMENT.txt TASKS.txt
+
+## to prepare next Debian upstream source tarball
+dfsg: dfsg-master
+dfsg-%:
+	git checkout dfsg
+	-git merge --no-commit $*
+	-git rm -rf scikits/image/externals/joblib
+	# -git rm -f ./scikits/image/svm/src/libsvm/svm.*
+	git commit -m "Merge $* into DFSG (pruning externals: joblib)" -a
+	git checkout debian
